name = "jmichaels-marketing-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jmichaels-db"
database_id = "a1c24fd8-8902-411b-bd7f-ba63b93e550d"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "jmichaels-images"

[vars]
ENVIRONMENT = "production"